spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
  main:
    banner-mode: off

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioAdmin}
  secret-key: ${MINIO_SECRET_KEY:minioPassword123}
  bucket: ${MINIO_BUCKET:documents}

logging:
  level:
    root: info
    org.springframework.amqp: info