security:
#  jwt-secret: 6f9pUe8m2lQw3r9Zc1Jv7xK4tP2a5s8Dq0Hn3b6Rk9Uu1y4Wz7N0g==
  jwt-secret: ${JWT_SECRET}
  jwt-ttl-seconds: 3600
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioAdmin}
  secret-key: ${MINIO_SECRET_KEY:pwd4minioAdmin} # fine for dev but for prod ->leave this out, right?
  bucket: ${MINIO_BUCKET:documents}