services:
  postgres:
    image: "postgres:16"
    container_name: postgres
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  api:
    build: ./rest
    container_name: api
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
      build: ./frontend       # multistage Dockerfile is used
      ports:
        - "8080:80"           # currently used due to 'currently' blocked port
      depends_on:
        - api

      networks: [paperless]

volumes:
  pgdata:

networks:
  paperless:
    driver: bridge
