services:
  postgres:
    image: "postgres:16"
    container_name: postgres
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks: [paperless]

  rabbit:
    image: rabbitmq:3.13-management
    container_name: dms-rabbit
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS:-guest}

  api:
    build: ./rest
#    container_name: api
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      STORAGE_UPLOAD_DIR: /data/uploads
    depends_on:
      - postgres
    ports: []
#      - "8081:8081"
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER:-guest}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS:-guest}
    depends_on:
      - postgres
      - rabbit
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [paperless]

  # ---- Web UI / Frontend + NginX Proxy ----
  webui:
      build: ./frontend       # multistage Dockerfile is used
      depends_on:
        - api
      ports:
        - "80:80"
      networks: [paperless]

  ocr-worker:
    build: ./ocr-worker
    environment:
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: ${RABBIT_USER:-guest}
      RABBIT_PASS: ${RABBIT_PASS:-guest}
    depends_on:
      - rabbit

volumes:
  pgdata:
  uploads:

networks:
  paperless:
    driver: bridge
