services:
  postgres:
    image: "postgres:16"
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks: [paperless]

  rabbit:
    image: rabbitmq:3.13-management
    container_name: dms-rabbit
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS:-guest}
    networks: [paperless]

  # ---- MinIO - Datastorage -----
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-}
      # MINIO_BROWSER_REDIRECT_URL: "https://localhost:9000"
    volumes:
      - minio-data:/data  # persist data
    ports:
      - "9000:9000"
      - "9001:9001"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks: [paperless]

  api:
    build: ./rest
    #    container_name: api
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/mydatabase
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: secret
#      STORAGE_UPLOAD_DIR: /data/uploads
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER:-guest}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASS:-guest}

      # MinIO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: documents
    depends_on:
      - postgres
      - rabbit
      - minio
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [paperless]

  # ---- Web UI / Frontend + NginX Proxy ----
  webui:
    build: ./frontend # multistage Dockerfile is used
    depends_on:
      - api
    ports:
      - "80:80"
    networks: [paperless]

  ocr-worker:
    build: ./ocr-worker
    environment:
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: ${RABBIT_USER:-guest}
      RABBIT_PASS: ${RABBIT_PASS:-guest}

      # MinIO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: documents

    depends_on:
      - rabbit
      - minio
    networks: [paperless]
    restart: unless-stopped

volumes:
  pgdata:
#  uploads:
  minio-data:


networks:
  paperless:
    driver: bridge
